trigger:
  - main  # Kendi branch'ınıza göre ayarlayın

pool:
  vmImage: 'ubuntu-latest'  # Windows için 'windows-latest' de seçilebilir

steps:
  # Maven build için adım
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean verify'  # 'clean test' yerine 'verify', test + raporlama
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'  # Java 17 kullanılıyor
      options: '-DskipTests=false'  # Testleri çalıştırmak için false olarak ayarlandı
      mavenOpts: '-Xmx1024m'  # JVM memory ayarı, gerekirse artırabilirsiniz

  # Test sonuçlarını yayınlama
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/failsafe-reports/*.xml'  # Surefire/Failsafe raporları
      mergeTestResults: true
    condition: succeededOrFailed()  # Test başarısız olsa bile devam et

  # Test sonuçlarını pipeline'da arşivle
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/target'
      artifact: 'test-results'
      publishLocation: 'pipeline'

  # Cucumber raporunu oluştur ve yayınla (isteğe bağlı)
  - script: |
      echo "Cucumber raporunu oluşturuyor"
      mvn net.masterthought:maven-cucumber-reporting:generate
    displayName: 'Cucumber Raporu Oluştur'
