# Ana branch'e push yapıldığında pipeline tetiklenecek.
trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'AzureStorage'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean verify'
      options: '-DskipTests=false'
      mavenOpts: '-Xmx1024m'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/failsafe-reports/*.xml'
      mergeTestResults: true
    condition: succeededOrFailed()
