# Ana branch'e push yapıldığında pipeline tetiklenecek.
trigger:
  - main  # Kendi branch'ınıza göre ayarlayın.

pool:
  vmImage: 'ubuntu-latest'  # Alternatif: 'windows-latest' de kullanılabilir.

steps:
  # Java sürümünü indir ve ayarla.
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'AzureStorage'  # Azure Storage'dan indirilebilir veya pre-installed seçebilirsiniz.

  # Maven build işlemini gerçekleştir.
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'  # Projenin pom.xml dosyasını belirtiyor.
      goals: 'clean verify'  # 'clean verify', testleri ve raporlamayı içerir.
      options: '-DskipTests=false'  # Testlerin çalıştırılması.
      mavenOpts: '-Xmx1024m'  # JVM memory ayarı, gerekirse artırabilirsiniz.

  # Test sonuçlarını yayınla.
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/failsafe-reports/*.xml'  # Surefire ve Failsafe raporları.
      mergeTestResults: true  # Test sonuçları birleştirilsin.
    condition: succeededOrFailed()  # Testler başarısız olsa da pipeline devam eder.
